# TestCompile.yml
# Github workflow script to test compile all examples of an Arduino library repository.
#
# Copyright (C) 2020-2025  Armin Joachimsmeyer
# https://github.com/ArminJo/Github-Actions
#

# This is the name of the workflow, visible on GitHub UI.
name: TestCompile

on:
  workflow_dispatch: # To run it manually
    description: 'manual build check'
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
    - '**.ino'
    - '**TestCompile.yml'

jobs:
  build:
    name: Test compiling examples for Uno
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout new BlueDisplay library
        uses: actions/checkout@v3
        with:
          repository: ArminJo/Arduino-BlueDisplay
          ref: master
          path: CustomLibrary_BD # must contain string "Custom"
          # Must remove BlueDisplay from REQUIRED_LIBRARIES

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@master
        with:
          sketch-names: SimpleTouchScreenDSO.ino
#          required-libraries: BlueDisplay # Serves as access layer to local display libraries
